GRUB - only validate configuration only if Secure Boot is active
This sets the /boot/efi/EFI/onie/grub.cfg to detect
if Secure Boot is active. If it is, it selects
/mnt/onie-boot/grub/grub_sb.cfg, and keeps
GRUB signature checking enabled.

If Secure Boot is not active, then
GRUB signature checking is disabled, and
/mnt/onie-boot/grub/grub.cfg is used as
the configuration file.

Note that grub.cfg and grub_sb.cfg
start out as identical files.

This allows for grub.cfg to be modified
for system test/debug/recovery at the
cost of not having Secure boot active.

This commits includes a patch to grub 2.04 that
implements the is_sb_active module, used by
the config script to check the state of
Secure Boot

Tests:
1 )
Delete the signature for the config file
with all the settings:
rm /mnt/onie-boot/grub_sb.cfg.sig
Boot should halt in GRUB until Secure Boot
is disabled.
Note: altering grub_sb.cfg should not be possible
as it has the immutable bit set (lsattr grub_sb.cfg)

2 )
Delete the signature for the config file
that does the secure boot check
rm /boot/efi/EFI/onie/grub.cfg.sig
System should be unable to boot beyond GRUB
regardless of Secure Boot setting.

Signed-off-by: Andriy Dobush <andriyd@nvidia.com>
Signed-off-by: Alex Doyle <adoyle@nvidia.com>

diff --git a/installer/grub-arch/install-arch b/installer/grub-arch/install-arch
--- a/installer/grub-arch/install-arch
+++ b/installer/grub-arch/install-arch
@@ -33,7 +33,6 @@ usage_arch=$(cat <<EOF
 		Target ONIE install device.  Must be a valid block device.
 EOF
 )
-
 # Parse architecture specific installer args
 parse_arg_arch()
 {
@@ -547,37 +546,54 @@ install_grub_config()
     if [ -r $boot_dir/onie/grub/grub-variables ] ; then
         . $boot_dir/onie/grub/grub-variables
     fi
-	# Only if building Secure Grub for a UEFI system
+
+    # Only if building Secure Grub for a UEFI system
     if [ "$image_secure_grub" = "yes" ] && [ "$install_firmware" = "uefi" ] ; then
-		# Copy the Secure Boot grub config over
+        # Store a copy of the grub config to be used instead if Secure Boot is disabled.
+        # These files are generated by onie/installer/grub-arch/grub.d/51_onie_grub_secure_boot
+        #
+
+        # Populate /mnt/onie-boot/grub
         cp grub_sb.cfg $grub_root_dir/grub.cfg || {
-            echo "ERROR: copying grub config to destatition: $grub_root_dir"
+            echo "ERROR: copying grub_sb.cfg to destination: $grub_root_dir"
             exit 1
         }
-		# And detached signature
-        cp grub_sb.cfg.sig $grub_root_dir/grub.cfg.sig || {
-            echo "ERROR: copying grub config  sig to destatition: $grub_root_dir"
+        # gpg signature for grub config
+        cp grub_sb.cfg.sig $grub_root_dir/grub_sb.cfg.sig || {
+            echo "ERROR: copying grub_sb.cfg.sig to destination: $grub_root_dir"
             exit 1
         }
-		# Copy the config for Secure boot disabled
+        # Copy the config for Secure boot disabled
         # Set the immutable bit to prevent modification of this file.
-		# Traditionally the NOS has been able to modify the grub.cfg.
-		# However, now that GRUB will be comparing it to a detached signature
-		# before loading it, any changes to that file will render the system
-		# unbootable.
-		if [ -e /boot/efi/EFI/onie/grub.cfg ];then
-			# If there is an existing install, overwrite it with a new
-			# copy that matches the signatures.
-			chattr -i /boot/efi/EFI/onie/grub.cfg
-		fi
-        chattr +i $grub_root_dir/grub.cfg		
-        cp grub.cfg /boot/efi/EFI/onie/grub.cfg || {
-            echo "ERROR: copying grub config to destatition: /boot/efi/EFI/onie"
+        # Traditionally the NOS has been able to modify the grub.cfg.
+        # However, now that GRUB will be comparing it to a detached signature
+        # before loading it, any changes to that file will render the system
+        # unbootable.
+        if [ -e $grub_root_dir/grub_sb.cfg ];then
+            # If there is an existing install, overwrite it with a new
+            # copy that matches the signatures.
+            chattr -i $grub_root_dir/grub_sb.cfg
+        fi
+        # grub config file, that is used if uefi secure boot is enabled
+        cp grub_sb.cfg $grub_root_dir/grub_sb.cfg || {
+            echo "ERROR: copying grub_sb.cfg to destatition: $grub_root_dir"
             exit 1
         }
-		# And detached signature		
+        chattr +i $grub_root_dir/grub_sb.cfg
+
+        # Being under /boot/efi, this is the first grub.cfg file loaded.
+        # It references the grub files (grub_sb.cfg, grub.cfg ) installed
+        #  in grub_root_dir
+        # ( Note: both have the same content for now)
+        # This grub.cfg  checks if Secure Boot is enabled.
+        #  If not, GRUB signature checking is disabled from here on out.
+        cp grub.cfg /boot/efi/EFI/onie/grub.cfg || {
+            echo "ERROR: copying grub.cfg to destination: /boot/efi/EFI/onie"
+            exit 1
+        }
+        # Copy detached signature. This grub.cfg is always validated.
         cp grub.cfg.sig /boot/efi/EFI/onie/grub.cfg.sig || {
-            echo "ERROR: copying grub config to destatition: /boot/efi/EFI/onie"
+            echo "ERROR: copying grub.cfg.sig to destination: /boot/efi/EFI/onie"
             exit 1
         }
     else
@@ -775,18 +791,38 @@ install_uefi_loader()
     install_grub_config $boot_dir
 
     # Create default EFI loader BOOT/BOOTX64.efi
-	if [ "$image_secure_boot" = "yes" ] && [ "$install_firmware" = "uefi" ] ; then
-        local loader_dir="${uefi_dir}/EFI/onie"
-        local BOOT_dir="${uefi_dir}/EFI/BOOT"
-        mkdir -p $BOOT_dir
-        cp -f $loader_dir/* ${BOOT_dir}/ || {
-            echo "ERROR: Unable to copy loader directory: $loader_dir to ${BOOT_dir}"
-            return 1
-        }
-        if [ -f ${BOOT_dir}/mmx64.efi ] ; then
-            rm -f ${BOOT_dir}/mmx64.efi
-        fi
+    local loader_dir="${uefi_dir}/EFI/onie"
+    local BOOT_dir="${uefi_dir}/EFI/BOOT"
+    mkdir -p $BOOT_dir
+    cp -rf $loader_dir/* ${BOOT_dir}/ || {
+        echo "ERROR: Unable to copy loader directory: $loader_dir to ${BOOT_dir}"
+        return 1
+    }
+    if [ "$image_secure_boot" = "yes" ]; then
+        # Make shim default fallback loader
         mv "${BOOT_dir}/shimx64.efi" "${BOOT_dir}/BOOTX64.EFI"
+        # Remove not needed mmx from /BOOT folder
+        if [ -f ${BOOT_dir}/mm${image_uefi_arch}.efi ] ; then
+            rm ${BOOT_dir}/mm${image_uefi_arch}.efi
+        fi
+        # Remove fallback efi file from efi/onie
+        if [ -f $loader_dir/fb${image_uefi_arch}.efi ] ; then
+            rm $loader_dir/fb${image_uefi_arch}.efi
+        fi
+        if [ -e "$onie_root_dir/grub/BOOT.CSV_secured" ] ; then
+            mv "$onie_root_dir/grub/BOOT.CSV_secured" "${loader_dir}/BOOT.CSV"
+        fi
+        if [ -e "$onie_root_dir/grub/BOOT.CSV" ] ; then
+            rm "$onie_root_dir/grub/BOOT.CSV"
+        fi
+    else
+        mv "${BOOT_dir}/grubx64.efi" "${BOOT_dir}/BOOTX64.EFI"
+        if [ -e "$onie_root_dir/grub/BOOT.CSV" ] ; then
+            mv "$onie_root_dir/grub/BOOT.CSV" "${loader_dir}/BOOT.CSV"
+        fi
+        if [ -e "$onie_root_dir/grub/BOOT.CSV_secured" ] ; then
+            rm "$onie_root_dir/grub/BOOT.CSV_secured"
+        fi
     fi
 }
 
@@ -914,6 +950,10 @@ install_image()
             echo "Error: Problems installing GRUB on device: ${onie_boot_dev}, $onie_boot_mnt"
             exit 1
         }
+        # Clean BOOT.CSV file that is relevant just for UEFI boot
+        if ls "$onie_root_dir/grub/"BOOT.CSV* 1> /dev/null 2>&1; then
+            rm "$onie_root_dir/grub/"BOOT.CSV*
+        fi
     fi
 
     # Restore the previous grubenv file
